### ISSUE TITLE
ふりがなの修正

### ISSUE THREAD

**Issue by atmiro16** [Mr-Kyary-at-eg/git_tutorial_with_m#11]
文章中のふりがなを修正する。

**Comment by atmiro16** [comment]
ブランチ名に迷ったので、issues追加しました。

**Comment by Mr-Kyary-at-eg** [comment]
@atmiro16 
良いと思います。Issueと紐づけてブランチを管理するのはIssueドリブンって言い方をしたりします。
ちゃんとそれに則っているわけではないですが、似たようなやり方なのでこれでいいかと。

**Comment by atmiro16** [comment]
@Mr-Kyary-at-eg 
よかったです。
issueドリブン調べてみます。

**Comment by atmiro16** [comment]
#12にて対応済み。
